name: 新たな記事をデプロイ

on:
  push:
    branches:
      - main
    paths:
      - 'src/blog/src/pages/posts/**'

run-name: 新たな記事をデプロイ

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_IAM_ROLE_ARN: ${{ secrets.AWS_IAM_ROLE_ARN }}

  NODE_VERSION: 20
  SOURCE_DIR: src/blog

  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  CLOUDFRONT_ID: ${{ secrets.CLOUDFRONT_ID }}
  GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}

  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_USERNAME: GitHub Actions
  SLACK_SUCCESS_MESSAGE: "新たな記事のデプロイに成功しました。"
  SLACK_FAILURE_MESSAGE: "新たな記事のデプロイに失敗しました。"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # 入力値チェック
      - name: Target validate
        if: ${{ github.event_name != 'push' }}
        run: exit 1

      # チェックアウト
      - name: Checkout Branch
        uses: actions/checkout@v4

      # Node.jsのセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      # ODICによるAWS認証
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_IAM_ROLE_ARN }}
          role-session-name: GitHubActions-${{ github.run_id }}
      
      # ビルド
      - name: Build
        working-directory: ${{ env.SOURCE_DIR }}
        run: |
          echo PUBLIC_GOOGLE_ANALYTICS_ID=${{ env.GOOGLE_ANALYTICS_ID }} > .env.production
          npm install
          npm run build

      # S3へのデプロイ
      - name: Deploy Next.js to S3
        working-directory: ${{ env.SOURCE_DIR }}
        run: |
          aws s3 sync --region ${{ env.AWS_REGION }} dist s3://${{ env.BUCKET_NAME }} --delete
      
      # CloudFrontのキャッシュ削除
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_ID }} --paths "/*"

      # Slack通知
      - name: Slack notification on success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: ${{ env.SLACK_USERNAME }}
          SLACK_COLOR: good
          SLACK_MESSAGE: ${{ env.SLACK_SUCCESS_MESSAGE }}

      - name: Slack notification on failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: ${{ env.SLACK_USERNAME }}
          SLACK_COLOR: danger
          SLACK_MESSAGE: ${{ env.SLACK_FAILURE_MESSAGE }}
          